baseURL = "https://karikowska.github.io/"
languageCode = 'en-us'
title = 'Karolina K.'
theme = 'hugo-noir'

# URL handling
relativeURLs = true
canonifyURLs = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
name = "Karolina K."
location = "London, UK"
description = "Always ready to learn and innovate. Approachable, early-career engineer who's eagerly dipping her toes in leadership and creating impact."
profile_image = "/images/profile.jpg"
discord = "scionofdarkness"
github = "https://github.com/karikowska"
email = "karo.a.kowalska@gmail.com"
linkedin = "https://linkedin.com/in/karolina-a-kowalska"
linkedin_username = "karolina-a-kowalska"

[[params.experience]]
company = "GSK"
role = "Digital and Tech Associate (Future Leader Programme)"
period = "Sept 2024 - Present"
logo = "/images/logo/gsk.png"
description = "First rotation in Supply Chain - working on AI, Digital Twins and Autonomous Systems. Stack: AzureML, Python, pytest"
responsibilities = [
    "Key responsibility with specific achievement",
]

[[params.experience]]
role = "Events and Partnerships Lead"
company = "Uplift, a GSK UK ERG"
period = "Jan 2025 - Present"
description = "Liaising with external partners and subject matter experts to design and organise events for hundreds of members, with the aim of spreading awareness and educating about social mobility within the organisation."
responsibilities = ["- Managing a team of three to design and organise events for hundreds of members, while reporting directly to the co-founders and other leads",
"- My events have led to membership in ERG increasing by 150%< since I started and being awarded GSK Bronze Award",
"- Learning how to navigate complex environment and policies within a large corporate organisation, influence and manage others effectively"
]


[[params.experience]]
company = "Durham University"
role = "MEng Computer Science"
period = "Sept 2020 - July 2024"
logo = "/images/logo/dur.png"
description = "First Class Honours. Thesis: 71%"
responsibilities = [
    "- Worked as a teaching assistant for Computer Systems module for two years, teaching and helping break down complex concepts for 150+ students",
    "- Software Engineering - Successfully led a team of colleagues over an academic year to construct an educational web app for neurodivergent children",
    "- Project Management - Successfully managed a team of software engineering students to build a QnA web app - received a 90% approval rating from engineers for my management style and 81% for my final report",
    "- Human-AI Interaction - Despite having a team member drop out, I successfully led a team of 8 to build a mobile AI-powered flashcard app under intense time pressure of a month",
]

[[params.projects]]
    title = "Velu - AI-Powered Product & Price Scraper"
    description = "I collect figures in my free time, and I check their prices frequently... to save on time, I've offloaded this task onto an LLM! Given the item I want to find and the website, the LLM autonomously searches and fetches me the most relevant items and their prices."
    tech = "Python, BeautifulSoup4, LangChain"
    image = "/images/projects/project1.png"
    link = "https://github.com/karikowska/price-scraper"

[[params.voluntary]]
role = "Mentor"
organization = "ZeroGravity, Stemettes, GSK"
period = "Sept 2024 - Present"
description = "I've mentored almost ten young people thus far. I love supporting them on their career/university journey and helping them find out where their passion and skills can take them :)"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
  [[menu.main]]
    name = "Contact Me"
    url = "/contact/"
    weight = 5